spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    restart:
      exclude: static/**, public/**
  http:
    multipart:
      location: upload
      max-file-size: 100MB
      max-request-size: 500MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hereyou?autoReconnect=true&useSSL=true&verifyServerCertificate=false
    username: hereYou
    password: hereYou1!
  social:
    facebook:
      appId: 793471174138586
      appSecret: 8bd93c8c3d77a71f6c26339a595cdb03
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  type-aliases-package: kr.ac.hansung.maldives.web.model
  mapper-locations:
    - classpath:mapper/*-sql.xml
  configuration:
    map-underscore-to-camel-case: true

security:
  basic:
    enabled: true

whereyou:
  google-map-api-key: AIzaSyCZqKafyvL0OerIRPWS_XV9GhPcWPIAL_w
  fusion-table-id: 1_hzEAwwva6MTOdWw6gN-uU7L2ikjeW5tnGqXWj-P
  eval-point: 5